### ISSUE TITLE
Error found: compilation error

### ISSUE THREAD

**Issue by ankit039** [BalajiG2000/Casino-game#1]
As, i tried to run this on https://ideone.com/ but it show error as i have attached the image of that error or you can check that error by clicking this link >> https://ideone.com/yfMvHl

![Capture](https://user-images.githubusercontent.com/44525721/63634108-882f9500-c66f-11e9-9903-ee232779a1dd.JPG)

**Comment by BalajiG2000** [comment]
I wrote this code in Borland Turbo C++ ,which is the oldest and discontinued IDE for C++ programming language. The current versions of c++ such as C++14 will not support the header file format i have used. I will change this according to current C++14 version. Thanks Ankit.
